build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 10
  ComplexMethod:
    threshold: 15
  TooManyFunctions:
    thresholdInFiles: 25
    thresholdInClasses: 25
    thresholdInInterfaces: 25
    thresholdInObjects: 25
    thresholdInEnums: 25

style:
  MaxLineLength:
    maxLineLength: 120
  MagicNumber:
    active: false
  ReturnCount:
    max: 4
  ForbiddenComment:
    active: false

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    constantPattern: '[A-Za-z][_A-Za-z0-9]*'
  VariableNaming:
    variablePattern: '[a-zA-Z][_A-Za-z0-9]*'

exceptions:
  TooGenericExceptionCaught:
    active: false
